# EasyHub 综合设置

# 一些特殊名词
# true 打开
# false 关闭
# String 字符串
# StringList 字符串列表
# Int 整数
# Double 小数
# Boolean 属于true和false的爸爸

# 防止玩家移动背包内的物品
# 开关 可填: true/false  默认关闭
preventMoveItem: false

# 防止生成怪物
# 开关 可填: true/false  默认关闭
preventSpawnMob: false

# 防止掉落物品
# 开关 可填: true/false  默认开启
preventDropItem: true

# 防止方块燃烧
# 开关 可填: true/false  默认开启
preventBlockBurn: true

# 防止玩家破坏方块
# 开关 可填: true/false  默认开启
preventPlayerBreakBlock: true

# 防止玩家放置方块
# 开关 可填: true/false  默认开启
preventPlayerPlaceBlock: true

# 防止玩家饱食度改变
# 开关 可填: true/false  默认开启
preventPlayerFoodLevelChange: true

# 防爆
# 开关 可填: true/false  默认开启
antiExplosion: true

# 防止玩家恶意攻击他人
# 开关 可填: true/false  默认开启
preventPlayerHitOthers: true

# 防止玩家脚滑而造成的伤害(掉落伤害)
# 开关 可填: true/false  默认开启
preventPlayerFallDamage: true

# 清除玩家死亡信息
# 开关 可填: true/false  默认开启
clearDeathMessage: true

# 防止玩家拾取物品
# 开关 可填: true/false  默认开启
preventPickupItem: true

# 防止玩家旋转展示框
# 开关 可填: true/false  默认开启
preventInteractItemFrame: true

# 开局清空玩家背包
# 开关 可填: true/false  默认开启
clearInventory: true

# 开局治疗玩家, 包括饱食度
# 开关 可填: true/false  默认开启
healPlayer: true

# 强制玩家出生在出生点
# 开关 可填: true/false 默认关闭
forceSpawnPoint: false

# 掉落至虚空自动返回在出生点
# 开关 可填: true/false  默认开启
voidReturn: true

# 自定义帮助列表
customHelp:
  # 自定义帮助列表开关 可填 true/false 默认关闭
  switch: false
  checkCommands:
    - "/help"
    - "/帮助"
    - "/h"
  message:
    - "&e&l&m一一一一&r &7[ &6服务器帮助列表 &7] &e&l&m一一一一"
    - "&f输入 &a&l/help &f或 &a&l/帮助 &f你可以随时随地输入这个指令来获得帮助~"
    - "&f输入 &a&l/spawn &f返回主城"
    - "&f你可以输入 &a&l/xxx &f来赞助服务器哦~"
    - "&f你知道吗? 这个插件作者的&c&lQQ&f其实是: &a&l666666 &f一般人我都不告诉他~"

# 无雨世界表设置
weather:
  # 无雨设置开关 可填 true/false 默认开启
  switch: true
  # 无雨世界表 可填 StringList
  worlds:
    - "world"
    - "shengcun"

# 时间设定
time:
  # 时间设定开关 可填 true/false 默认开启
  switch: true
  # 时间设定表
  # 格式: 世界名:时间
  #   可填的时间: sun_rise, day, noon, sun_set, night, mid_night
  #   它们分别是 日出, 白天, 中午, 日落, 夜晚, 午夜
  worlds:
    - "world:noon"
    - "shengcun:day"

# 插件列表隐藏
antiPluginDetect:
  # 开关 可填 true/false 默认开启
  switch: true
  # 需要防止的指令们
  checkCommands:
    - "/?"
    - "/about"
    - "/version"
    - "/plugins"
    - "/bukkit:?"
    - "/bukkit:about"
    - "/bukkit:version"
    - "/bukkit:plugins"
  # 当玩家输入上方的指令时, 插件自动提示如下信息
  message: "&fPlugins (1): &aEasyHub"

# 自定义加入与离开服务器信息
customJoinLeaveMessage:
  # 自定义信息开关
  # 开关 可填: true/false 默认关闭
  enable: false
  # 加入相关
  join:
    # 拥有权限 vip.1 的玩家所显示的内容
    1:
      permission: "vip.1"
      message:
        - "&f&l&m一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一"
        - ""
        - "        &a天空一声巨响, 只见人群中钻出一个身影, Ta竟然是尊贵的 &eVIP1"
        - "                &f尊敬的 &a&l%player% &f加入了游戏!"
        - ""
        - "&f&l&m一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一"
    2:
      permission: "vip.2"
      message:
        - "&f&l&m一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一"
        - ""
        - "        &a天空一声巨响, 只见人群中钻出一个身影, Ta竟然是尊贵的 &eVIP2"
        - "                &f尊敬的 &a&l%player% &f加入了游戏!"
        - ""
        - "&f&l&m一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一"
    # op所显示的内容
    op:
      - "&f亲爱的狗管理 &c&l%player% &f加入了游戏!"
    # 默认玩家所显示的内容
    default:
      - "&f亲爱的 &a&l%player% &f加入了游戏!"
  # 离开相关
  leave:
    # 拥有权限 vip.1 的玩家所显示的内容
    1:
      permission: "vip.1"
      message:
        - "&f&l&m一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一"
        - ""
        - "                &f尊敬的 &a&l%player% §8[§6VIP2§8]&f离开了游戏!"
        - ""
        - "&f&l&m一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一"
    2:
      permission: "vip.2"
      message:
        - "&f&l&m一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一"
        - ""
        - "                &f尊敬的 &a&l%player% §8[§6VIP2§8]&f离开了游戏!"
        - ""
        - "&f&l&m一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一"
    # op所显示的内容
    op:
      - "&f亲爱的狗管理 &c&l%player% &f离开了游戏!"
    # 默认玩家所显示的内容
    default:
      - "&f亲爱的 &a&l%player% &f离开了游戏!"
