# EasyHub 综合设置

# 一些特殊名词
# true 打开
# false 关闭
# String 字符串
# StringList 字符串列表
# Int 整数
# Double 小数
# Boolean 属于true和false的爸爸


# 无雨世界表设置
weather:
  # 无雨设置开关 可填 true/false
  switch: true
  # 无雨世界表 可填 StringList
  worlds:
    - "world"
    - "shengcun"

# 时间设定
time:
  # 时间设定开关 可填 true/false
  switch: true
  # 时间设定表
  # 格式: 世界名:时间
  #   可填的时间: sun_rise, day, noon, sun_set, night, mid_night
  #   它们分别是 日出, 白天, 中午, 日落, 夜晚, 午夜
  worlds:
    - "world:sun_rise"
    - "shengcun:noon"